// Generated by CoffeeScript 1.6.3
(function() {
  var $, defaultConfig;

  $ = jQuery;

  defaultConfig = {
    target: '[require]',
    errorClass: 'error',
    event: 'blur',
    submitBtn: false,
    debug: false,
    beforeCallback: function() {},
    afterCallback: function() {}
  };

  $.fn.validate = function(opts) {
    opts = $.extend({}, defaultConfig, opts);
    return this.each(function() {
      var ident, self;
      self = $(this);
      ident = opts.target;
      self.attr("novalidate", "novalidate");
      validateSubmit.call(this, opts);
      self.on('focusein', ident, function() {});
    });
  };

}).call(this);
