// Generated by CoffeeScript 1.6.3
(function() {
  var $, checkForm, defaultConfig, validate, validateSubmit;

  $ = jQuery;

  defaultConfig = {
    ident: '[require]',
    errorClass: 'error',
    isParent: false,
    event: 'blur',
    submitBtn: false,
    debug: false,
    beforeCallback: function() {},
    afterCallback: function() {}
  };

  validateSubmit = function(opts) {
    var self;
    self = this;
    if (opts.submitBtn) {
      self.delegate(opts.submitBtn, 'click', function(evt) {
        return self.trigger('submit');
      });
      self.submit(function(evt) {
        if (opts.debug) {
          evt.preventDefault();
          return false;
        }
        if (!checkForm.call(self, opts)) {
          return false;
        }
      });
    }
  };

  checkForm = function(opts) {
    var field, items;
    items = this.find(opts.ident);
    field = [];
    items.each(function() {
      (field = validate.call(this, opts.errorClass, opts.isParent)) && field.push(this);
    });
    return !field.length;
  };

  validate = function(errCls, isParent) {};

  $.fn.validate = function(opts) {
    opts = $.extend({}, defaultConfig, opts);
    return this.each(function() {
      var ident, self;
      self = $(this);
      ident = opts.ident;
      self.attr("novalidate", "novalidate");
      validateSubmit.call(this, opts);
      self.on('focusein', ident, function() {});
    });
  };

}).call(this);
